### ISSUE TITLE
Integrate netlify previews & DCO checks

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#10]
This would be a requirement going ahead, hence getting netlify and DCO integrated would make sense.

- Process for integrating netlify - https://github.com/apps/netlify
- Process for integrating DCO - https://github.com/apps/dco

**Comment by veenamj-avesha** [comment]
We have integrated DCO. 

We will get DevOps help if we need to integrate netlify. So, I'm closing this issue for now.
