### ISSUE TITLE
Integrating Docusaurus search functionality

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#11]
Process to integrate Algolia search
- Reach out to Algolia and get the API key
- API key needs to be included in docusaurus.config.js

**Comment by veenamj-avesha** [comment]
@divya-mohan0209   - The Docusaurus search functionality is added on the KubeSlice opensource website by @that-backend-guy's team. Website: https://docs.avesha.io/documentation/open-source/0.2.0

Can we close this issue?

**Comment by divya-mohan0209** [comment]
I think we are good to close the issue, thanks!
