### ISSUE TITLE
Typos to be corrected across the documentation website

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#14]
[This page](https://docs.avesha.io/documentation/open-source/0.2.0/getting-started-with-kind-clusters) has a typo in the Note section for Ubuntu. The term entered here is ulimt. It should be ulimit.

In a similar fashion, there are multiple such spelling errors across the website that need to be corrected. I'd like to propose a prose linter for helping with this.

- [ ] Fix current typos in existing documentation
- [ ] Develop a customized spell-linter

**Comment by Akshit42-hue** [comment]
Hey @divya-mohan0209, can I work on it

**Comment by divya-mohan0209** [comment]
Hey @Akshit42-hue , sure! Please let me know if you need any further information. 

A brief of what we're expecting:

- a prose linter that runs when a PR is submitted against the docs repo. This would mean, integrating the linter into the GH action.
- This linter should pick on spelling mistakes. For KubeSlice & cloud-native, terms it'd be better if we have an "ignore list" that the linter can refer while running so that these are not flagged.

**Comment by Akshit42-hue** [comment]
Can I used [GitHub Spellcheck](https://github.com/marketplace/actions/github-spellcheck)

> Hey @Akshit42-hue , sure! Please let me know if you need any further information.
> 
> A brief of what we're expecting:
> 
> * a prose linter that runs when a PR is submitted against the docs repo. This would mean, integrating the linter into the GH action.
> * This linter should pick on spelling mistakes. For KubeSlice & cloud-native, terms it'd be better if we have an "ignore list" that the linter can refer while running so that these are not flagged.

**Comment by divya-mohan0209** [comment]
@Akshit42-hue - That sounds like a good option. Why don't you open up a thread on our Slack channel to discuss if there's any other suggestion/preference that the community folks have? #kubeslice on the Kubernetes Slack, if you're already not on it.

**Comment by Akshit42-hue** [comment]
> @Akshit42-hue - That sounds like a good option. Why don't you open up a thread on our Slack channel to discuss if there's any other suggestion/preference that the community folks have? #kubeslice on the Kubernetes Slack, if you're already not on it.

Great idea. on it

**Comment by divya-mohan0209** [comment]
Hey @Akshit42-hue , just checking in. Have we made any progress on this?

**Comment by Akshit42-hue** [comment]
Hey @divya-mohan0209, I cannot find any alternartive  of [Github spellchecker](https://github.com/marketplace/actions/github-spellcheck) and there are some typo which need to be corrected shall I raise a PR ?

**Comment by divya-mohan0209** [comment]
Hey Axit, you may raise a PR. But the long term goal is to find a spell-linter / write one customized to our requirement. I shall divide the issue into two tasks from which you can tick off the first one then.

**Comment by divya-mohan0209** [comment]
Did you raise a PR or was it resolved by someone else?

**Comment by sayantani11** [comment]
I think I may have something for this. But will have to dig a little more!

**Comment by sayantani11** [comment]
Yeah I think I can develop a customized spell linter! @divya-mohan0209 I can give this one a try, if @Akshit42-hue is fine with that.

**Comment by Akshit42-hue** [comment]
Go ahead @sayantani11  but before that let's discuss your idea on slack so others can give suggestions :)

**Comment by sayantani11** [comment]
@divya-mohan0209 Presently the spellcheck is working fine, we need to now focus on correcting typos across documentation and adding more words to the list, cause as i can see from another PR, the check is failing for typos across the website. I'll try to fix the typos and add necessary technical words to the list.

**Comment by ashutosh887** [comment]
@Akshit42-hue @divya-mohan0209 
Let me work on this if not resolved so far

**Comment by veenamj-avesha** [comment]
We have been working on the spell check issue. So, I will close this issue.
