### ISSUE TITLE
Creation of kind-based tutorial on Gitpod/Killercoda

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#16]
A good way to help folks who are new to the KubeSlice experience is to give them a demo environment that they can run Kind clusters and create slices in. 

We can approach this problem in either of these two ways: 

- Gitpod & Killercoda allow you to create ephemeral dev environments directly from the Git repository. The [examples GitHub repo](https://github.com/kubeslice/examples) can be used as the base repo from which the script for kind clusters & tutorial can be executed after installation of the pre-requisites. 
- Alternately, we have an ephemeral dev environment embedded into our docs like we have with Kubernetes tutorials and create a separate tutorial section.

**Comment by veenamj-avesha** [comment]
We now have a demo to install KubeSlice on Kind clusters using the kubeslice-cli tool. So, I'm closing this issue.
