### ISSUE TITLE
Refactoring of Overview section

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#17]
The current [overview section for docs](https://kubeslice.io) needs refactoring to include the following things in a sectional format:

- Concise description of what multi-tenancy is and what are the challenges associated with multi-tenancy in a multi-cluster Kubernetes environment
- What KubeSlice is
- Brief description of KubeSlice's value prop

**Comment by verma-kunal** [comment]
Hey @divya-mohan0209

**Comment by akshayamadhuri** [comment]
@verma-kunal  is it still open

**Comment by veenamj-avesha** [comment]
The overview section is revamped from version 1.0.0. So, I'm closing this issue. 

https://kubeslice.io/documentation/open-source/1.0.0/
