### ISSUE TITLE
Refactor the KiND cluster setup documentation

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#39]
The [KiND cluster setup documentation](https://kubeslice.io/documentation/open-source/0.2.0/getting-started-with-kind-clusters) has bad UX due to it being one continuous long page. Akin to what's there in the [Cloud Cluster setup section](https://kubeslice.io/documentation/open-source/0.2.0/getting-started-with-cloud-clusters/), this part needs to be broken up & sectioned appropriately.

Content doesn't need to be added per se since most of the existing content is perfectly fine. Only gaps need to be filled.

**Comment by 26tanishabanik** [comment]
@divya-mohan0209 , I would like to work on this issue, kindly  assign this issue to me

**Comment by 26tanishabanik** [comment]
@divya-mohan0209 , Kindly review the PR #40 , suggest any changes if required

**Comment by ashutosh887** [comment]
@divya-mohan0209 Please let me work on the issue
