### ISSUE TITLE
Require to make changes in the Wording of `Prerequisites` section in `README.md` file

### ISSUE THREAD

**Issue by amolmote** [kubeslice/docs#43]
Problem:
  I have nodejs version 16.13.1 installed but still not able to run the application because nodejs version is not meet to the 
expected Node js version.

Changes Required:
   I know this is kind of silly mistake. but it will require to  fix. In Prerequisites section it is mentioned that to run the application
we require to have the `Node js version 14 or greater`  but it is not true. Require to modify the wording. Please refer this SS.
![issue](https://user-images.githubusercontent.com/98871024/187125964-9afda09f-024d-4d5e-9e2b-8154bfe17244.PNG)

Excuse me if this issue is not valid.but I thought we require to fix any minor mistake.

**Comment by sayantani11** [comment]
I am facing the same error and still not able to solve it :(

**Comment by amolmote** [comment]
@sayantani11 , install the latest available version of Node js. It will work
![runningapp](https://user-images.githubusercontent.com/98871024/187613596-3d890559-d307-479f-a8ca-dfae57e06dbc.PNG)

**Comment by amolmote** [comment]
please comment,what others think about this, do we need to change the wordings about this `node version`?

**Comment by amolmote** [comment]
if not then i will close this issue.

**Comment by amolmote** [comment]
sure @divya-mohan0209, please assign it to me

**Comment by divya-mohan0209** [comment]
I've assigned it to you. Please open a PR :)
