### ISSUE TITLE
Explain various concepts related to KubeSlice in a dedicated page

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#5]
Some of the terms like
- Slice boundaries
- RFC1918 network addresses
- Architectural components from [this page](https://docs.avesha.io/documentation/open-source/0.2.0/architecture)

could benefit from a page on the website.

**Comment by sayantani11** [comment]
I would like to work on it!!

**Comment by divya-mohan0209** [comment]
Hello @sayantani11 , please go for it. I've assigned the issue to you :) Thank you!

**Comment by sayantani11** [comment]
@divya-mohan0209 One question- where will that page go in the website?

**Comment by divya-mohan0209** [comment]
Hello @sayantani11 , it will be the first section after overview.

**Comment by ashutosh887** [comment]
@sayantani11 Did your PR get merged? If not, @divya-mohan0209 I would like to work on the issue

**Comment by veenamj-avesha** [comment]
We have revamped the overview section from version 1.0.0, So, I'm closing this issue. 

https://kubeslice.io/documentation/open-source/1.0.0/
