### ISSUE TITLE
Add a contributing guide section within the docs

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#7]
Contribution guides for 
- Documentation
- Overall project

to be created & added to the docusaurus website.

**Comment by sayantani11** [comment]
@divya-mohan0209 Can I be assigned this?

**Comment by divya-mohan0209** [comment]
Hey @sayantani11 , this is already done per #23 . I'll be closing this one out :) There are a few suggestions in the comments that need remediating, so will be opening a separate issue/PR for that.
