### ISSUE TITLE
Community links to redirect to K8s Slack and Google Groups

### ISSUE THREAD

**Issue by divya-mohan0209** [kubeslice/docs#8]
The community link should redirect to the K8s Slack channel + Google Groups on these pages - 
1. https://docs.avesha.io/documentation/open-source/0.2.0/community.
2. https://docs.avesha.io/documentation/open-source/0.2.0/getting-started-with-kind-clusters
3. https://docs.avesha.io/documentation/open-source/0.2.0/getting-started-with-cloud-clusters/

Links:

- [K8s Slack channel link](https://slack.k8s.io)

We have two Google Groups:
- [KubeSlice Users](https://groups.google.com/g/kubeslice-users)
- [KubeSlice Development Discussions](https://groups.google.com/g/kubeslice-dev)

**Comment by AmanSarraf** [comment]
/assign @AmanSarraf
I would like to work on this

**Comment by divya-mohan0209** [comment]
Hello Aman, sure. Please feel free to contribute a PR against this repo with the changes.

**Comment by AmanSarraf** [comment]
AFAIK https://docs.avesha.io/documentation/open-source/0.2.0/getting-started-with-cloud-clusters/ has multiple subpages unlike others so where the join links are supposed to be placed? @divya-mohan0209

**Comment by divya-mohan0209** [comment]
In the index page itself, that the hyperlink points to there is a community link.

**Comment by AmanSarraf** [comment]
since I added the join links to the community page in the last PR, so is it okay if I simply redirect to the ```getting-started-with-kind-clusters``` and  ```getting-started-with-cloud-clusters``` Page?

**Comment by divya-mohan0209** [comment]
No, that will not do.

The first thing that I'd have liked to see on the community page is a rewrite. It unfortunately got merged before I could sign off on it. 

But the first thing that I wanted to be edited out is the part about KubeSlice discussions. That is not how we're seeking feedback.

The second thing on the community page that I want is the capitalization of the word Kubernetes in [this heading](https://docs.avesha.io/documentation/open-source/0.2.0/community#join-kubeslice-on-kubernetes-slack)

Also, please adhere to the DCO and sign off your commits in the proper manner.

**Comment by divya-mohan0209** [comment]
Once the above is done, I'd expect a change on the kind & cloud cluster index pages to either the community page or an individual mention of the slack/google groups.

**Comment by AmanSarraf** [comment]
OK what I need to add or update in the KubeSlice discussions

**Comment by divya-mohan0209** [comment]
The KubeSlice discussions link points to the GitHub discussions. You can eliminate that part currently and have the community page reflect only Slack & Google groups.

**Comment by ashutosh887** [comment]
I can take this issue @divya-mohan0209 Ma'am

**Comment by veenamj-avesha** [comment]
We've removed the community page from our sidebar after we revamped the docs. So, I'm closing this issue.
